(import (chicken string))
(define (cartesian-product . lists)
  (define (product-of-two xs ys)
    (define (cons-on-each-ys x)
      (map (lambda (y) (list->string (car (append x y))))
           ys))
    (apply append (map cons-on-each-ys xs)))
  (foldr product-of-two '(()) lists))
(cartesian-product (string->list "abcdefgh") (string->list "12345678"))
